language: python 
services:
 - redis-server 
before_script:
 - make
 - git submodule init
 - git submodule update
 - cd vendor/shielded && npm install && cd ../..
 - ./env/bin/pip install pytest
script: cd tests && ../env/bin/py.test
notifications:
  email: false
  irc: 
    channels:
      - "irc.freenode.org#shields"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true

