public:
  bind:
    address: '::'

  metrics:
    prometheus:
      enabled: false

  ssl:
    isSecure: false

  cors:
    allowedOrigin: []

  persistence:
    dir: './private'

  services:
    github:
      baseUri: 'https://api.github.com/'
      debug:
        enabled: false
        intervalSeconds: 200
    trace: false

  profiling:
    makeBadge: false

  cacheHeaders:
    defaultCacheLengthSeconds: 120

  rateLimit: true

  handleInternalErrors: true

  integrations:
    DynamicJson:
      fetchLimit: '2MB'

    DynamicXml:
      fetchLimit: '128KB'

    DynamicYaml:
      fetchLimit: '64KB'

    default:
      fetchLimit: '10MB'

private: {}
